title: Jhon Jairo Realpe
theme: jekyll-theme-minimal

logo: /assets/img/headshot_circle.png
email: jhonjarealpe@gmail.com

plugins:
  - jekyll-seo-tag

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
